### ISSUE TITLE
If logging requests that include file uploads in form data, this generates an error by attempting to encode with UTF-8

### ISSUE THREAD

**Issue by Halloran** [renuo/rails_api_logger#6]

**Comment by coorasse** [comment]
This issue should also be solved in version 0.7.0. Please let me know

**Comment by ldes-karibew** [comment]
I still have the issue on versions 0.7.0 and 0.9.0.
In request_log.rb:
`  def self.from_request(request, loggable: nil)
    request_body = (request.body.respond_to?(:read) ? request.body.read : request.body)
    body = request_body&.dup&.force_encoding("UTF-8")
    begin
      body = JSON.parse(body) if body.present?
    rescue JSON::ParserError
      body
    end
    create(path: request.path, request_body: body, method: request.method, started_at: Time.current, loggable: loggable)
  end
`
The call to body.present? throw the error "Puma caught this error: invalid byte sequence in UTF-8 (ArgumentError)".
